### ISSUE TITLE
ask Kirsten and Audrey to look over doc and fill in stories.

### ISSUE THREAD

**Issue by ed-g** [stumpsyn/stumpsyn#54] opened 2016-04-16 23:51 UTC
https://docs.google.com/document/d/1rlKenw62JHWm8YiAmHJ7psqaqaO_5TEYSVZzzfDBp1o/edit?usp=sharing

**Comment by elea** [comment] 2016-04-16 23:52
This is a duplicate of #41

**Closed by elea** 2016-04-16 23:52 UTC
Labels: communicatons
